spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/getlife
    username: root
    password: 1234

logging:
  level:
    root: INFO
  org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
